### PR TITLE
Plpy interrupt

### PR DESCRIPTION
**Pull request by jgoizueta**
Some fixes and enhancements for more reliable plpython execution interruption.

### CODE REVIEW

**Comment by jgoizueta** [comment]
Two main improvements here:
* Avoiding SIGINTs received during the execution of one plpython function (or while not executing plpython code) to affect a different plplython function
* More reliable interruption (python exceptions where delayed due to the `Py_AddPendingCall` function returning 0 rather than -1)

Also minor fixes for correctness that affect none of CARTO operations to support SIG_DFL, SIG_IGN signal handler.

**Comment by ethervoid** [comment]
Glad you find a way to improve this patch. Great work, looks great for me :)))))

**Comment by rafatower** [comment]
while trying to generate the package from the sources:
```
$ debuild -uc -us
...
dpkg-source: error: expected [ +-] at start of line 24 of diff 'postgresql-9.5.2/debian/patches/92-plpython-interrupt.patch'
dpkg-source: info: applying 92-plpython-interrupt.patch
dpkg-source: info: the patch has fuzz which is not allowed, or is malformed
dpkg-source: info: if patch '92-plpython-interrupt.patch' is correctly applied by quilt, use 'quilt refresh' to update it
dpkg-buildpackage: error: dpkg-source --before-build postgresql-9.5.2 gave error exit status 2
debuild: fatal error at line 1376:
dpkg-buildpackage -rfakeroot -D -us -uc failed
```

I'll try to get it fixed.

**Comment by rafatower** [comment]
It should be soon available for testing here: https://launchpad.net/~cartodb/+archive/ubuntu/postgresql-next

**Comment by rafatower** [comment]
@azamorano or @jvillarf can you please take a look?

**Comment by rafatower** [comment]
@jgoizueta one last check?

**Comment by jgoizueta** [comment]
:+1: I've checked the effect of the final patch and it matches the intended code, which I've also updated in https://github.com/CartoDB/postgres/pull/5 (it had some extraneous characters there as @ethervoid had noticed). Thanks for taking care of this!

**Pull request merged**
